- hosts: "{{ hosts }}"
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "deploy {{ src }} to {{ dest }} "
      template: src={{ src }} dest={{ dest }} mode=644
